### ISSUE TITLE
https://bountyprogram.origintrail.io/ not able to submit new form

### ISSUE THREAD

**Issue by Valcyclovir** [OriginTrail/dkg-docs#11]
I am unable to submit a new application form to the https://bountyprogram.origintrail.io/ website using the designated space below 
"Step 1: Subscribe for the bounty program through this form"

When I press submit, the website will just hang and I get no confirmation that the application is submitted. The telemetry is also not picking up my node. 

email: swag.grenox@gmail.com
wallet: 0x8d4573DCB247b67310cD08CB03B0AE161aBAd2a3

I tried replicating this on mobile using a different sign in, same error with the following:
email: testnet@otnoderunner.com
wallet: 0x0F6343D264065500bf3f7e0120652E4Ca946EAa6

Please add these two credentials to your participant database and let me know if I should run other tests to see why the form is not working !

UPDATE: 2022-03-10
Just to follow up on the bug, the website now returns a ERROR page after trying to submit the form. 

I would also suggest to make it clearer as to whether the form is required in order to participate on the bounty. As it stands now, no one new can fill up the form, or if they did, they have absolutely no way to tell if their email is linked to their telemetry wallet address and earnings bounty points. The new [medium article ](https://medium.com/origintrail/launching-today-run-a-v6-origintrail-node-earn-trac-rewards-fe984a49603b) tells people can run separate nodes with different wallet addresses but with the bug on this form, they are unable to do so.

**Comment by Niks988** [comment]
Hi Valcyclovir, we have tested the form multiple times and unfortunately did not manage to reproduce the issues you were describing so if possible, please try submitting the informations one more time.

Also, can you provide us with some additional informations on the issue such as:
- which browser are you using
- did you try clearing the cache or using incognito mode

After checking your submissions, so far we have the following informations:

**Submission 1:** 
Email: swag.grenox@gmail.com
Github name: /
Wallet address: 0x23e7f99b5e63aede48ee04c14a5266f54e7460e2

**Submission 2:** 
Email: otnode@otnoderunner.com
Github name: /
Wallet address: 0x5575221EFfEfAA4a4866430985AF2c0ba8BDb099

Submission 3: 
Email: otnode@otnoderunner.com
Github name: /
Wallet address: 0xffAB286Ed71D8Bb8d14Cd7119aF9420EAE49ca0c

Please let us know if you managed to submit the new wallet addresses.

**Comment by Valcyclovir** [comment]
Upon testing again, it turns out my pihole is blocking connection to static.mailerlite.com preventing the page from loading. The page is working as intended now showing "Thank you for subscribing".

For future reference, close all adblocking and filters before attempting to subscribe and the page will load.

Thanks and closing issue.
